/**
 * Vehicle Data — Brand → Model → Year hierarchy
 *
 * v2 architecture: NO runtime WC API calls.
 * Vehicle hierarchy is loaded from a build-time generated JSON cache.
 * Cache is generated by scripts/generate-vehicle-cache.ts
 */

import type { VehicleHierarchy, VehicleBrand } from "@/types/woocommerce";
import { slugify } from "./utils";

// Known car brands — longest match first for multi-word brands
export const KNOWN_BRANDS: string[] = [
  "Alfa Romeo",
  "Aston Martin",
  "Land Rover",
  "Mercedes Benz",
  "Mercedes-Benz",
  "Rolls Royce",
  "Rolls-Royce",
  "Great Wall",
  "Aiways",
  "Alfa",
  "Alpine",
  "Audi",
  "BMW",
  "BYD",
  "Bentley",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Cupra",
  "DS",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Dodge",
  "FAW",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Iveco",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lada",
  "Lamborghini",
  "Lancia",
  "Lexus",
  "Lincoln",
  "Lotus",
  "MAN",
  "MG",
  "MINI",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Polestar",
  "Porsche",
  "Renault",
  "Rover",
  "Saab",
  "Seat",
  "SEAT",
  "Skoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "VW",
  "DAF",
  "Scania",
];

/**
 * Parse a vehicle attribute string into brand + model + years.
 */
export function parseVehicleString(
  str: string
): { brand: string; model: string; years: string } | null {
  const trimmed = str.trim();
  if (!trimmed) return null;

  // Try known brands (longest match first)
  let matchedBrand = "";
  const lower = trimmed.toLowerCase();
  for (const b of KNOWN_BRANDS) {
    const bLower = b.toLowerCase();
    if (lower.startsWith(bLower + " ") || lower === bLower) {
      if (b.length > matchedBrand.length) {
        matchedBrand = b;
      }
    }
  }

  if (!matchedBrand) {
    const spaceIdx = trimmed.indexOf(" ");
    if (spaceIdx === -1) return null;
    matchedBrand = trimmed.substring(0, spaceIdx);
  }

  const brandFromInput = trimmed.substring(0, matchedBrand.length);
  const rest = trimmed.substring(matchedBrand.length).trim();
  if (!rest) return null;

  // Extract years from the end
  const yearsPatterns = [
    /\b(Baujahr\s+ab\s+\d{4})$/i,
    /\b(ab\s+Baujahr\s+\d{4})$/i,
    /\b(ab\s+\d{4})$/i,
    /\b(\d{4}\s*[-\u2013]\s*\d{4})$/,
    /\b(seit\s+\d{4})$/i,
  ];

  let years = "";
  let modelPart = rest;

  for (const pattern of yearsPatterns) {
    const ym = rest.match(pattern);
    if (ym) {
      years = ym[1].trim();
      modelPart = rest.substring(0, rest.length - ym[0].length).trim();
      break;
    }
  }

  modelPart = modelPart.replace(/\(\s*\)\s*$/, "").trim();
  if (!modelPart) return null;

  return { brand: brandFromInput, model: modelPart, years };
}

/**
 * Extract base model name, stripping variant suffixes.
 */
export function extractBaseModel(model: string): string {
  let base = model.replace(/\s*\([^)]*\)/g, "").trim();
  base = base
    .replace(/\s+(4x[24]|4\*[24]|AllRad|Bj|ab\s+\d{4}|aus\s+.*)$/i, "")
    .replace(/\s+\d+\.?\s*Gen$/i, "")
    .trim();
  base = base.replace(/\s+\d+$/, "").trim();
  return base || model;
}

function normalizeBrand(brand: string): string {
  if (brand.length <= 3 && brand === brand.toUpperCase()) return brand;
  return brand.charAt(0).toUpperCase() + brand.slice(1).toLowerCase();
}

/**
 * Build vehicle hierarchy from raw vehicle strings.
 * Used by the cache generation script.
 */
export function buildVehicleHierarchy(
  vehicleStrings: string[]
): VehicleBrand[] {
  const brandMap = new Map<
    string,
    {
      displayName: string;
      models: Map<
        string,
        {
          displayName: string;
          years: Set<string>;
          productCount: number;
        }
      >;
    }
  >();

  for (const str of vehicleStrings) {
    const parsed = parseVehicleString(str);
    if (!parsed) continue;

    const brandKey = parsed.brand.toLowerCase();
    const baseModel = extractBaseModel(parsed.model);
    const modelKey = baseModel.toLowerCase();

    if (!brandMap.has(brandKey)) {
      brandMap.set(brandKey, {
        displayName: normalizeBrand(parsed.brand),
        models: new Map(),
      });
    }

    const brand = brandMap.get(brandKey)!;
    if (!brand.models.has(modelKey)) {
      brand.models.set(modelKey, {
        displayName:
          baseModel.charAt(0).toUpperCase() + baseModel.slice(1),
        years: new Set(),
        productCount: 0,
      });
    }

    const modelEntry = brand.models.get(modelKey)!;
    modelEntry.productCount++;
    if (parsed.years) {
      modelEntry.years.add(parsed.years);
    }
  }

  const brands: VehicleBrand[] = [];
  const sortedBrands = [...brandMap.entries()].sort((a, b) =>
    a[0].localeCompare(b[0])
  );

  for (const [, brandData] of sortedBrands) {
    const models = [...brandData.models.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([, modelData]) => ({
        name: modelData.displayName,
        slug: slugify(modelData.displayName),
        yearRanges: [...modelData.years].map((y) => {
          const match = y.match(/(\d{4})\s*[-\u2013]\s*(\d{4})/);
          return {
            slug: slugify(y),
            label: y,
            startYear: match ? parseInt(match[1]) : 0,
            endYear: match ? parseInt(match[2]) : 0,
          };
        }),
        productCount: modelData.productCount,
      }));

    brands.push({
      name: brandData.displayName,
      slug: slugify(brandData.displayName),
      models,
      productCount: models.reduce((sum, m) => sum + m.productCount, 0),
    });
  }

  return brands;
}

// ─── Cache Loading (build-time JSON) ────────────────────

let cachedHierarchy: VehicleHierarchy | null = null;

export function getVehicleHierarchy(): VehicleHierarchy {
  if (cachedHierarchy) return cachedHierarchy;

  try {
    // Dynamic require for JSON file — works at build time
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require("../../data/vehicle-hierarchy.json") as VehicleHierarchy;
    cachedHierarchy = data;
    return data;
  } catch {
    // Return empty hierarchy if cache doesn't exist yet
    console.warn("Vehicle hierarchy cache not found. Run: npm run generate-vehicle-cache");
    return { brands: [], lastUpdated: "" };
  }
}

export function getBrandBySlug(slug: string): VehicleBrand | undefined {
  return getVehicleHierarchy().brands.find((b) => b.slug === slug);
}
